import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/themes.css";
import { AuthRefresh } from "../ui/authRefresh/authRefresh";

export const metadata: Metadata = {
  title: "Lad stack overflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthRefresh />
        {children}
      </body>
    </html>
  );
}
